myset: myset.o set.o use_set.o
	gcc myset.o set.o use_set.o -o myset

myset.o: myset.c
	gcc -pedantic -Wall -ansi myset.c -o myset.o

set.o: set.c
	gcc -pedantic -Wall -ansi set.c -o set.o

use_set.o: use_set.c
	gcc -pedantic -Wall -ansi use_set.c -o use_set.o