#ifndef ASSEMBLER_DEFENITIONS_H
#define ASSEMBLER_DEFENITIONS_H

#define WORD_SIZE 14
#define NUMBER_SIZE 12
#define LABEL_SIZE 31
#define MAX_LINES 100

enum tables {
    INSTRUCTIONS=1, DATA, SYMBOL, ERROR
};

#endif //ASSEMBLER_DEFENITIONS_H
